### ISSUE TITLE
SVG icons are not showing colour, they're being filled in with a black color

### ISSUE THREAD

**Issue by Sterlingryan** [uqmessias/react-native-svg-renderer#21]
Im trying to render a number of SVG icons, but they're all filled in with the colour black:

![Simulator Screen Shot - iPhone Xs - 2020-06-12 at 15 28 17](https://user-images.githubusercontent.com/15817814/84507593-5a304580-acc1-11ea-9491-d15dc06993b7.png)

This is the code:

```
export default class BankList extends Component {
    renderItem = ({ item }) => {
        const { onPress } = this.props;
        return (
            <TouchableOpacity style={[Styles.paddingHorizontal, { height: Dimensions.buttonHeight, width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }]} onPress={() => onPress(item.id)}>
                <View style={{ flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center' }}>
                    <SVG
                        width={Dimensions.mediumProfilePictureSize}
                        height={Dimensions.mediumProfilePictureSize}
                        source={{ uri: item.icon }} />
                    <Text style={[Styles.titleText, { marginLeft: Dimensions.horizontalMargin / 2 }]}>{item.displayable_name}</Text>
                </View>
                <Image
                    style={{ height: hp('2%'), width: wp('2.7%'), resizeMode: 'contain' }}
                    source={nextIcon} />
            </TouchableOpacity>
        );
    }

    render() {
        const { banksData } = this.props;
        return (
            <FlatList
                keyExtractor={item => item.id}
                data={banksData}
                renderItem={this.renderItem}
            />
        );
    }
}
```

**Comment by uqmessias** [comment]
@Sterlingryan, thanks fo opening this issue!

Which version are you using? Can you provide some of these SVG URIs so I can debug it?

**Comment by Sterlingryan** [comment]
@uqmessias

Here are the versions :

"react-native-svg-renderer": "^0.2.0",
"react-native": "0.59.10",
"react-native-svg": "^9.5.1"

and here's a link to an icon:

https://truelayer-client-logos.s3-eu-west-1.amazonaws.com/banks/banks-icons/ob-natwest-icon.svg

**Comment by uqmessias** [comment]
@Sterlingryan, unfortunately, the React Native SVG Renderer doesn't support css inside a SVG yet.

If you have access to these SVG, please, use the properties `fill` and `stroke` to define their colors.

**Comment by Sterlingryan** [comment]
I see, I'll see what I can do, thanks for the prompt reply @uqmessias. I appreciate your work 👍
