### ISSUE TITLE
Exception is thrown when trimElementChildren is ran in some cases

### ISSUE THREAD

**Issue by gregersn** [uqmessias/react-native-svg-renderer#4]
The following line is throwing an exception with `ReferenceError: child is not defined` in certain cases. 

https://github.com/uqmessias/react-native-svg-renderer/blob/2baf2fca024b1824a1e587b4ad65fd72dc64c136/index.js#L168

Seems like throwing in a `var`, `let` or `const` there will solve that problem
`    for (var child of children) {`

**Comment by uqmessias** [comment]
@gregersn,
Thank you for reporting this!

In which cases is this happening? Do you have a reproducible example?

**Comment by gregersn** [comment]
Sadly I can't remember the exact case that triggered `trimElementChildren` , but the variable `child` is not declared, so that this has worked at all is a mystery to me. 

I would also use `for(let child of children)` instead of `var`

**Comment by uqmessias** [comment]
> Sadly I can't remember the exact case that triggered trimElementChildren , but the variable child is not declared, so that this has worked at all is a mystery to me.

I didn't face this error yet, but if it appears again, please, report it here or submit a PR and I'll be glad to review or investigate it.

> I would also use for(let child of children) instead of var

I'm planning to refactor the lib, in order to make it clearer and easier for others to contribute.
Thanks tho.

**Comment by gregersn** [comment]
I'll see if I can isolate a test case, but here is the trace:

```console.error node_modules/react-native-svg-renderer/index.js:324
    ERROR SVG ReferenceError: child is not defined
        at SvgRenderer.trimElementChilden (/projecfolder/node_modules/react-native-svg-renderer/index.js:168:252)
        at SvgRenderer.createSVGElement (/projecfolder/node_modules/react-native-svg-renderer/index.js:177:12)
        at SvgRenderer.inspectNode (/projecfolder/node_modules/react-native-svg-renderer/index.js:300:19)
        at SvgRenderer.inspectNode (/projecfolder/node_modules/react-native-svg-renderer/index.js:292:29)
        at SvgRenderer.render (/projecfolder/node_modules/react-native-svg-renderer/index.js:316:28)
```

**Comment by uqmessias** [comment]
Thanks for commenting the trace here.

If you have at least the code that threw this error, it would be very helpful.
